site_name: 'Vapor 大型教程'
site_description: 'Learn Vapor and Practice'
site_url: 'https://github.com/wangzhizhou/The-Vapor-Mega-Tutorial'
site_author: 'wangzhizhou'

theme: 
  name: 'material'
  palette:
    primary: 'Green'
    accent: 'Orange'
  font: 
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  #logo: # 'images/logo.svg'
    # icon: 'cloud'
  language: 'zh'
  direction: 'ltr'
  # favicon: 'assets/images/favicon.ico'
  feature:
    tabs: true

repo_name: 'GitHub 仓库'
repo_url: 'https://github.com/wangzhizhou/The-Vapor-Mega-Tutorial'

copyright: 'Copyright &copy; 2018-20XX wangzhizhou'

extra:
  search:
    language: 'zh'
  social:
    - type: 'github'
      link: 'https://github.com/wangzhizhou'
  disque: ''

markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


# extra:
    # disqus: 'joker-vapor'

nav:
  - 主页: 
      - 介绍: 'index.md'
      - 开发环境: 'dev-env.md'
      - Vapor的能力: 'vapor-can-do.md'
      - 项目结构: 'project-structure.md'
      - 添加GET路由: 'add-routes.md'
      - 接收POST数据: 'accept-data.md'
      - 返回JSON数据: 'return-json.md'
      - 排错: 'error-fix.md'
      - HTTP基础: 'http-basic.md'
      - REST API: 'rest-api.md'
      - 异步: 'async.md'
      - 数据库: 'Fluent-Persisting-models.md'
      - 配置数据库: 'configure-database.md'
      - 数据库CRUD操作: 'CRUD.md'
      - Fluent查询操作: 'fluent-query.md'
      - 控制器: 'controller.md'
      - 父子关系: 'parent-children-relation.md'
      - 切换数据库: 'switch-database-postgreSQL.md'
      - 兄弟关系: 'sibiling-relation.md'
      - 测试: 'testing.md'
      - 测试优化: 'testing-refine.md'