#!/usr/bin/env bash

VENV="vblogenv"
if [ ! -d "$VENV" ]; then
    python3 -m venv --clear vblogenv
    source "$VENV/bin/activate"
    pip install -r requirements.txt
else
    source "$VENV/bin/activate"
fi
git push origin
mkdocs gh-deploy -f