#!/usr/bin/env bash

VENV_DIR="vblogenv"
if [ -d "${VENV_DIR}" ]; then
	rm -rfv ${VENV_DIR}
fi

python3 -m venv --clear vblogenv
source vblogenv/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
mkdocs build --clean -f config/mkdocs.yml
mkdocs serve -f config/mkdocs.yml
