INHERIT: ./mkdocs.extensions.yml

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/polyfill@0.1.0/index.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3.2.2/es5/tex-mml-chtml.min.js