site_name: Vapor 大型教程
site_description: Learn Vapor and Practice
site_url: https://github.com/wangzhizhou/The-Vapor-Mega-Tutorial
site_author: wangzhizhou

repo_name: GitHub 仓库
repo_url: https://github.com/wangzhizhou/The-Vapor-Mega-Tutorial
docs_dir: '../docs'
site_dir: '../site'

copyright: >
  Copyright &copy; 2018-2023 wangzhizhou -
  <a href="#__consent">Change Cookie Settings</a> <br/> 
  Powered By 
  <a href="https://www.mkdocs.org/" target="_blank">MkDocs</a>
  With Theme 
  <a href="https://squidfunk.github.io/mkdocs-material/" target="_blank">
      Material for MkDocs
  </a>

watch:
  - ../docs
  - ../config
  - ../overrides
  - ../includes

